name: Build and release plugins

on:
  push:
    paths:
      - "src/**/*.ts"
      - "index.d.ts"
      - "!package.json"
    branches:
      # We only want to create a new release when
      # - a pr is merged to main
      # - we push into main
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FIG_BOT_TOKEN }}
      # Install all dependencies
      - name: install
        run: npm install
      # Transpile all plugins from ts to js
      - name: build
        run: npm run build
      - name: "Automated Version Bump"
        id: "version-bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.FIG_BOT_TOKEN }}
        with:
          skip-tag: "true"
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Rebuild Index
        run: npm run update-plugins -- $(git diff --name-only origin/main HEAD -- src/plugins/**/*.ts)
        env:
          PLUGINS_UPDATE_TOKEN: ${{ secrets.PLUGINS_UPDATE_TOKEN }}
